export const WHATSAPP_NUMBER = "5521981720710";
export const ADMIN_PASSWORD = "rafa123";
export const PIX_KEY = "43577769000180";
export const PIX_NAME = "Rafaela Sardinha Ferreira";
export const PIX_QR_CODE = "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/qrcode-pix_1_rilq1x";

export const BRAND = {
  logo: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/logo_fih38z",
  hero: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/banner_principal_ubjelk",
};

export const categories = [
  {
    id: "combos",
    name: "Combos",
    banner: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/banner_combos_opyqqk",
    description: "As melhores combinações para matar a fome.",
  },
  {
    id: "hamburgueres",
    name: "Hambúrgueres",
    banner: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/banne_hamburguer_oev7ts",
    description: "Montados do jeito que a fome merece.",
  },
  {
    id: "pasteis",
    name: "Pastéis",
    banner: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/banner_pasteis_svicgt",
    description: "Crocantes por fora, recheados por dentro.",
  },
  {
    id: "porcoes",
    name: "Porções",
    banner: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/banner_por%C3%A7%C3%B5es_ultb2k",
    description: "Perfeitas para compartilhar.",
  },
  {
    id: "bebidas",
    name: "Bebidas",
    banner: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/BANNER_BEBIDAS_gxdtxj",
    description: "A companhia perfeita para seu pedido.",
  },
];

const pastelImage = "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/pastel_rnjrrk";
const drinksBanner = "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/BANNER_BEBIDAS_tvwg3g";

export const initialProducts = [
  {
    id: "combo-1",
    category: "combos",
    name: "Combo Explosão de Sabores #1",
    price: 38,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/combo_1_shj2iy",
    description: "Batata suprema, salgadinhos, pastéis, nuggets e molhos.",
    status: "Disponível",
  },
  {
    id: "combo-2",
    category: "combos",
    name: "Combo Linguiça Insana #2",
    price: 43,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/combo_2_h3jivs",
    description: "Batata suprema, linguiça fina, nuggets, pastéis e molhos.",
    status: "Disponível",
  },
  {
    id: "combo-3",
    category: "combos",
    name: "Combo Crocância Suprema #3",
    price: 52,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/combo_3_fa0m7v",
    description: "Batata suprema, frango empanado, anéis de cebola, pastéis e molhos.",
    status: "Disponível",
  },
  {
    id: "combo-4",
    category: "combos",
    name: "Combo Rei da Fome #4",
    price: 62,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/COMBO_4_zvpm1p",
    description:
      "Batata suprema, anéis de cebola, 2 hambúrgueres, pastéis, nuggets, 1 Guaraná Antarctica 1L e molhos.",
    status: "Disponível",
  },
  {
    id: "combo-5",
    category: "combos",
    name: "Combo Pizza Mania #5",
    price: 60,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/combo_5_dwqxwl",
    description: "Batata suprema, anéis de cebola, pastéis, nuggets, mini pizzas e molhos.",
    status: "Disponível",
  },
  {
    id: "combo-6",
    category: "combos",
    name: "Combo Ataque Duplo #6",
    price: 78,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/combo_6_vkng5t",
    description: "Batata suprema, 4 hambúrgueres, nuggets, pastéis e molhos.",
    status: "Disponível",
  },
  {
    id: "combo-7",
    category: "combos",
    name: "Combo Família Feliz #7",
    price: 85,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/combo_7_l19mxd",
    description:
      "Batata suprema, anéis de cebola, pastéis, nuggets, mini pizzas, 1 Guaraná Antarctica 1L e molhos.",
    status: "Disponível",
  },
  {
    id: "combo-8",
    category: "combos",
    name: "Combo Fome Monstra #8",
    price: 100,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/combo_8_i7k3fe",
    description: "Batata suprema, frango empanado, pastéis, salgadinhos, mini pizzas e molhos.",
    status: "Disponível",
  },
  {
    id: "combo-9",
    category: "combos",
    name: "Combo Desafio da Rafa #9",
    price: 140,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/combo_9_jxtxgi",
    description: "Batata suprema, anéis de cebola, salgadinhos, pastéis, nuggets, 4 hambúrgueres e molhos.",
    status: "Disponível",
  },
  {
    id: "quarteto-campeao",
    category: "combos",
    name: "Quarteto Campeão",
    price: 30,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/quarteto_qva9kj",
    description:
      "Refrigerante, batata frita, nuggets e hambúrguer completo com pão, carne, queijo, presunto, anel de cebola, bacon, calabresa e cheddar.",
    status: "Disponível",
  },
  {
    id: "combo-casal",
    category: "combos",
    name: "Combo Casal",
    price: 50,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/COMBO_4_zvpm1p",
    description:
      "2 hambúrgueres completos, 400g de batata frita com cheddar e bacon, 1 Guaraná Antarctica 1L e molhos.",
    status: "Disponível",
  },
  {
    id: "hamburguer-completo",
    category: "hamburgueres",
    name: "Hambúrguer Completo",
    price: 18,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/hamburguer_1_a08lkp",
    description: "Hambúrguer completo com pão, carne, queijo, presunto, bacon, calabresa e cheddar.",
    status: "Disponível",
  },
  {
    id: "dois-hamburgueres-completos",
    category: "hamburgueres",
    name: "2 Hambúrgueres Completos",
    price: 32,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/duplo_burguer_ckf8uu",
    description: "Dois hambúrgueres completos com pão, carne, queijo, presunto, bacon, calabresa e cheddar.",
    status: "Disponível",
  },
  {
    id: "pastel-carne",
    category: "pasteis",
    name: "Pastel Carne",
    price: 10,
    image: pastelImage,
    description: "Pastel de 18cm recheado com carne.",
    status: "Disponível",
  },
  {
    id: "pastel-queijo",
    category: "pasteis",
    name: "Pastel Queijo",
    price: 10,
    image: pastelImage,
    description: "Pastel de 18cm recheado com queijo.",
    status: "Disponível",
  },
  {
    id: "pastel-pizza",
    category: "pasteis",
    name: "Pastel Pizza",
    price: 10,
    image: pastelImage,
    description: "Pastel de 18cm sabor pizza.",
    status: "Disponível",
  },
  {
    id: "pastel-frango-requeijao",
    category: "pasteis",
    name: "Pastel Frango com Requeijão",
    price: 12,
    image: pastelImage,
    description: "Pastel de 18cm recheado com frango e requeijão.",
    status: "Disponível",
  },
  {
    id: "pastel-frango-queijo",
    category: "pasteis",
    name: "Pastel Frango com Queijo",
    price: 12,
    image: pastelImage,
    description: "Pastel de 18cm recheado com frango e queijo.",
    status: "Disponível",
  },
  {
    id: "pastel-carne-queijo",
    category: "pasteis",
    name: "Pastel Carne com Queijo",
    price: 12,
    image: pastelImage,
    description: "Pastel de 18cm recheado com carne e queijo.",
    status: "Disponível",
  },
  {
    id: "pastel-carne-requeijao",
    category: "pasteis",
    name: "Pastel Carne com Requeijão",
    price: 12,
    image: pastelImage,
    description: "Pastel de 18cm recheado com carne e requeijão.",
    status: "Disponível",
  },
  {
    id: "pastel-queijo-requeijao",
    category: "pasteis",
    name: "Pastel Queijo e Requeijão",
    price: 12,
    image: pastelImage,
    description: "Pastel de 18cm recheado com queijo e requeijão.",
    status: "Disponível",
  },
  {
    id: "pastel-frango-requeijao-queijo",
    category: "pasteis",
    name: "Pastel Frango com Requeijão e Queijo",
    price: 14,
    image: pastelImage,
    description: "Pastel de 18cm recheado com frango, requeijão e queijo.",
    status: "Disponível",
  },
  {
    id: "pastel-carne-queijo-requeijao",
    category: "pasteis",
    name: "Pastel Carne com Queijo e Requeijão",
    price: 14,
    image: pastelImage,
    description: "Pastel de 18cm recheado com carne, queijo e requeijão.",
    status: "Disponível",
  },
  {
    id: "pastel-frango-calabresa-queijo",
    category: "pasteis",
    name: "Pastel Frango com Calabresa e Queijo",
    price: 14,
    image: pastelImage,
    description: "Pastel de 18cm recheado com frango, calabresa e queijo.",
    status: "Disponível",
  },
  {
    id: "pastel-frango-milho-requeijao",
    category: "pasteis",
    name: "Pastel Frango com Milho e Requeijão",
    price: 14,
    image: pastelImage,
    description: "Pastel de 18cm recheado com frango, milho e requeijão.",
    status: "Disponível",
  },
  {
    id: "pastel-carbonara",
    category: "pasteis",
    name: "Pastel Carbonara",
    price: 14,
    image: pastelImage,
    description: "Pastel de 18cm sabor carbonara.",
    status: "Disponível",
  },
  {
    id: "batata-media",
    category: "porcoes",
    name: "Batata Cheddar e Calabresa Média",
    price: 16,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/batata_frita_tf8hht",
    description: "Porção média de batata frita com cheddar e calabresa.",
    status: "Disponível",
  },
  {
    id: "batata-grande",
    category: "porcoes",
    name: "Batata Cheddar e Calabresa Grande",
    price: 30,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/batata_frita_tf8hht",
    description: "Porção grande de batata frita com cheddar e calabresa.",
    status: "Disponível",
  },
  {
    id: "guarana-1l",
    category: "bebidas",
    name: "Guaraná Antarctica 1L",
    price: 0,
    needsAdminPrice: true,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/guarana_antartica_1L_ceibss",
    description: "Guaraná Antarctica 1L.",
    status: "Disponível",
    visible: true,
  },
  {
    id: "coca-lata",
    category: "bebidas",
    name: "Coca-Cola Lata",
    price: 0,
    needsAdminPrice: true,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/coca_cola_fok7gz",
    description: "Coca-Cola lata.",
    status: "Disponível",
    visible: true,
  },
  {
    id: "guarana-lata",
    category: "bebidas",
    name: "Guaraná Lata",
    price: 0,
    needsAdminPrice: true,
    image: drinksBanner,
    description: "Guaraná Antarctica lata.",
    status: "Disponível",
    visible: true,
  },
  {
    id: "fanta-lata",
    category: "bebidas",
    name: "Fanta Lata",
    price: 0,
    needsAdminPrice: true,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/fanta_laranja_mvh1lx",
    description: "Fanta Laranja lata.",
    status: "Disponível",
    visible: true,
  },
  {
    id: "agua-mineral",
    category: "bebidas",
    name: "Água Mineral",
    price: 0,
    needsAdminPrice: true,
    image: "https://res.cloudinary.com/ddc8f5ani/image/upload/f_auto,q_auto/agua_mineral_kjiiy5",
    description: "Água mineral natural.",
    status: "Disponível",
    visible: true,
  },
];








